---
apiVersion: v1
kind: Pod
metadata:
  name: thebigtree
  labels:
    app: thebigtree
spec:
  restartPolicy: Always
  containers:
    - name: thebigtree
      image: thebigtree:latest
      imagePullPolicy: IfNotPresent
      env:
        - name: DISCORD_TOKEN
          value: "REPLACE_WITH_YOUR_DISCORD_BOT_TOKEN"
        - name: BIGTREE__BOT__guildid
          value: "REPLACE_WITH_YOUR_GUILD_ID"
        - name: BIGTREE__BOT__contest_dir
          value: "/data/contest"
        - name: BIGTREE__WEB__listen_host
          value: "0.0.0.0"
        - name: BIGTREE__WEB__listen_port
          value: "8443"
      ports:
        - containerPort: 8443
          hostPort: 8443
          protocol: TCP
      volumeMounts:
        - name: thebigtree-data
          mountPath: /data
  volumes:
    - name: thebigtree-data
      hostPath:
        path: /srv/thebigtree
        type: DirectoryOrCreate
