---
apiVersion: v1
kind: Pod
metadata:
  name: thebigtree-web
  labels:
    app: thebigtree-web
spec:
  restartPolicy: Always
  containers:
    - name: thebigtree-web
      image: ghcr.io/YOURORG/YOURREPO/thebigtree-web:latest
      imagePullPolicy: Always
      ports:
        - containerPort: 8080
          protocol: TCP
      env:
        - name: TZ
          value: "UTC"
      # Traefik (docker/podman provider) labels
      # Adjust entrypoints / TLS if your Traefik setup uses different names.
      labels:
        traefik.enable: "true"
        traefik.http.routers.rites.rule: "Host(`rites.thebigtree.life`)"
        traefik.http.routers.rites.entrypoints: "websecure"
        traefik.http.routers.rites.tls: "true"
        traefik.http.services.rites.loadbalancer.server.port: "8080"
