---
apiVersion: v1
kind: ConfigMap
metadata:
  name: thebigtree-config
data:
  bigtree.ini: |
    [BOT]
    DATA_DIR=/data
    contest_dir=/data/contest
    guildid=0000000000000000000
    token=<DISCORD_BOT_TOKEN>
    adminid=0000000000000000000
    priest_role_ids=[]
    elfministrator_role_ids=[]
    tarot_db=/data/tarot.json

    [openai]
    openai_api_key=<OPENAI_API_KEY>
    enable_priest_chat=True
    openai_model=gpt-4o-mini
    openai_temperature=0.7
    openai_max_output_tokens=400

    [WEB]
    listen_host=0.0.0.0
    listen_port=8443
    base_url=https://example.thebigtree.life:8443
    api_keys='["elfbingo","elfadmin"]'
    api_key_scopes='{"elfbingo":"bingo:admin","elfadmin":"admin:message,admin:announce,bingo:admin"}'

---
apiVersion: v1
kind: Pod
metadata:
  name: thebigtree
  labels:
    app: thebigtree
spec:
  restartPolicy: Always
  dnsPolicy: None
  dnsConfig:
    nameservers:
      - 1.1.1.1
      - 8.8.8.8
  containers:
    - name: thebigtree
      # Replace with your multi-arch image reference
      image: ghcr.io/YOURORG/YOURREPO/thebigtree:latest
      imagePullPolicy: Always
      env:
        # You can still override some things via env if needed
        - name: BIGTREE__BOT__contest_dir
          value: "/data/contest"
        - name: BIGTREE__BOT__DATA_DIR
          value: "/data"
        - name: BIGTREE__WEB__listen_host
          value: "0.0.0.0"
        - name: BIGTREE__WEB__listen_port
          value: "8443"
        - name: BIGTREE_CARDGAMES_DB_DIR
          value: "/opt/bigtree/database"
        - name: BIGTREE__DATABASE__host
          value: "127.0.0.1"
        - name: BIGTREE__DATABASE__port
          value: "5432"
        - name: BIGTREE__DATABASE__user
          value: "bigtree"
        - name: BIGTREE__DATABASE__password
          value: "treehouse"
        - name: BIGTREE__DATABASE__name
          value: "bigtree"
      ports:
        - containerPort: 8443
          hostPort: 8443   # change this if it conflicts on the host
          protocol: TCP
      volumeMounts:
        - name: thebigtree-data
          mountPath: /data
        - name: thebigtree-config
          mountPath: /opt/thebigtree/bigtree.ini
          subPath: bigtree.ini
        - name: thebigtree-local-db
          mountPath: /opt/bigtree/database
        - name: thebigtree-postgres
          mountPath: /var/lib/postgresql/data
    - name: thebigtree-web
      # Web gateway container (reverse proxy + cache)
      image: ghcr.io/YOURORG/YOURREPO/thebigtree-web:latest
      imagePullPolicy: Always
      ports:
        - containerPort: 8080
          hostPort: 8080   # change this if it conflicts on the host
          protocol: TCP
    - name: postgres
      image: postgres:15-alpine
      imagePullPolicy: IfNotPresent
      env:
        - name: POSTGRES_USER
          value: "bigtree"
        - name: POSTGRES_PASSWORD
          value: "treehouse"
        - name: POSTGRES_DB
          value: "bigtree"
      volumeMounts:
        - name: thebigtree-postgres
          mountPath: /var/lib/postgresql/data
  volumes:
    - name: thebigtree-data
      hostPath:
        path: /srv/thebigtree
        type: DirectoryOrCreate
    - name: thebigtree-config
      configMap:
        name: thebigtree-config
    - name: thebigtree-local-db
      hostPath:
        path: /opt/bigtree/database
        type: DirectoryOrCreate
    - name: thebigtree-postgres
      hostPath:
        path: /opt/bigtree/postgres
        type: DirectoryOrCreate
