---
apiVersion: v1
kind: ConfigMap
metadata:
  name: thebigtree-config
data:
  bigtree.ini: |
    [BOT]
    DATA_DIR=/data
    contest_dir=/data/contest
    guildid=0000000000000000000
    token=<DISCORD_BOT_TOKEN>
    adminid=0000000000000000000
    priest_role_ids=[]
    elfministrator_role_ids=[]
    tarot_db=/data/tarot.json

    [openai]
    openai_api_key=<OPENAI_API_KEY>
    enable_priest_chat=True
    openai_model=gpt-4o-mini
    openai_temperature=0.7
    openai_max_output_tokens=400

    [WEB]
    listen_host=0.0.0.0
    listen_port=8443
    base_url=https://example.thebigtree.life:8443
    api_keys='["elfbingo","elfadmin"]'
    api_key_scopes='{"elfbingo":"bingo:admin","elfadmin":"admin:message,admin:announce,bingo:admin"}'

---
apiVersion: v1
kind: Pod
metadata:
  name: thebigtree
  labels:
    app: thebigtree
spec:
  restartPolicy: Always
  containers:
    - name: thebigtree
      # Replace with your multi-arch image reference
      image: ghcr.io/YOURORG/YOURREPO/thebigtree:latest
      imagePullPolicy: Always
      env:
        # You can still override some things via env if needed
        - name: BIGTREE__BOT__contest_dir
          value: "/data/contest"
        - name: BIGTREE__BOT__DATA_DIR
          value: "/data"
        - name: BIGTREE__WEB__listen_host
          value: "0.0.0.0"
        - name: BIGTREE__WEB__listen_port
          value: "8443"
      ports:
        - containerPort: 8443
          hostPort: 8443   # change this if it conflicts on the host
          protocol: TCP
      volumeMounts:
        - name: thebigtree-data
          mountPath: /data
        - name: thebigtree-config
          mountPath: /opt/thebigtree/bigtree.ini
          subPath: bigtree.ini
  volumes:
    - name: thebigtree-data
      hostPath:
        path: /srv/thebigtree
        type: DirectoryOrCreate
    - name: thebigtree-config
      configMap:
        name: thebigtree-config
