---
apiVersion: v1
kind: ConfigMap
metadata:
  name: rites-starting-page
  labels:
    app: rites-starting
    role: error-page
    service: rites
  annotations:
    description: "Static startup page for rites.thebigtree.life"
data:
  index.html: |
    <!doctype html>
    <html lang="en">
    <head>
      <meta charset="utf-8" />
      <meta name="viewport" content="width=device-width,initial-scale=1" />
      <title>The Forest is Waking</title>
      <style>
        :root{
          --bg:#0f1a14;
          --glow:rgba(107,212,162,.28);
          --mist:rgba(214,178,110,.12);
          --panel:rgba(12,18,15,.7);
          --text:#e7f2ea;
          --muted:#9fb4a6;
        }
        *{box-sizing:border-box}
        body{
          margin:0;
          min-height:100vh;
          display:grid;
          place-items:center;
          background:
            radial-gradient(circle at 50% 20%, var(--mist), transparent 55%),
            linear-gradient(120deg, rgba(255,255,255,.04), transparent 60%),
            var(--bg);
          color:var(--text);
          font-family:"Spectral","Georgia",serif;
        }
        .wrap{
          text-align:center;
          padding:32px 24px;
          max-width:520px;
        }
        .pulse-wrap{
          width:220px;
          height:220px;
          margin:0 auto 18px;
          display:grid;
          place-items:center;
          position:relative;
        }
        .pulse-wrap::before{
          content:"";
          position:absolute;
          inset:12px;
          border-radius:50%;
          box-shadow:0 0 60px var(--glow);
          opacity:.6;
          animation:halo 2.6s ease-in-out infinite;
        }
        .heart{
          width:180px;
          height:180px;
          object-fit:contain;
          filter:drop-shadow(0 0 18px rgba(107,212,162,.5));
          animation:beat 1.6s ease-in-out infinite;
        }
        h1{margin:0 0 6px;font-size:28px;letter-spacing:.02em}
        p{margin:6px 0;color:var(--muted)}
        .status{
          margin-top:16px;
          padding:8px 14px;
          display:inline-flex;
          gap:10px;
          align-items:center;
          background:var(--panel);
          border-radius:999px;
          font-size:14px;
        }
        .dot{
          width:8px;height:8px;border-radius:50%;
          background:rgba(107,212,162,.7);
          animation:blink 1.4s ease-in-out infinite;
        }
        @keyframes beat{
          0%,100%{transform:scale(1)}
          40%{transform:scale(1.08)}
          60%{transform:scale(0.98)}
        }
        @keyframes halo{
          0%,100%{transform:scale(1);opacity:.45}
          50%{transform:scale(1.12);opacity:.2}
        }
        @keyframes blink{
          0%,100%{opacity:.3}
          50%{opacity:1}
        }
      </style>
    </head>
    <body>
      <div class="wrap">
        <div class="pulse-wrap">
          <img src="/thebigtree.png" alt="The Big Tree" class="heart" />
        </div>
        <h1>The Forest is waking</h1>
        <p>We are gathering the offerings. Your path will open shortly.</p>
        <div class="status"><span class="dot"></span><span id="statusText">Checking the rites...</span></div>
      </div>
      <script>
        const target = "/tarot/gallery";
        const statusText = document.getElementById("statusText");
        let attempts = 0;
        async function probe(){
          attempts += 1;
          try{
            const res = await fetch(target, {cache:"no-store"});
            if (res && res.ok){
              window.location.replace(target);
              return;
            }
          }catch(err){}
          statusText.textContent = `Checking the rites... (${attempts})`;
          setTimeout(probe, 2000);
        }
        probe();
      </script>
    </body>
    </html>
---
apiVersion: v1
kind: Pod
metadata:
  name: rites-starting
  labels:
    app: rites-starting
spec:
  containers:
    - name: rites-starting
      image: nginx:alpine
      ports:
        - containerPort: 8080
      volumeMounts:
        - name: rites-starting-html
          mountPath: /usr/share/nginx/html/index.html
          subPath: index.html
        - name: rites-starting-logo
          mountPath: /usr/share/nginx/html/thebigtree.png
          subPath: thebigtree.png
  volumes:
    - name: rites-starting-html
      configMap:
        name: rites-starting-page
    - name: rites-starting-logo
      hostPath:
        path: /opt/honsefarm/traefik/starting/thebigtree.png
        type: File
